name: 문서 배포

on:
  push:
    branches: [ "main" ]

# GitHub Pages 에 배포하기 위한 GITHUB_TOKEN 권한 설정
permissions:
  contents: read
  pages: write
  id-token: write
# 동시성 배포 허용
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: macos-13  #최신버전
    steps:
    - name: 체크아웃 🛎️
      uses: actions/checkout@v3
    - name: Setup Xcode version
      uses: maxim-lobanov/setup-xcode@v1 # xcode 버전 설정
      with:
        xcode-version: '15.0'
    - name: DocC 문서 빌드
      run: |
        xcodebuild docbuild -scheme swift-study \
          -derivedDataPath /tmp/docbuild \
          -destination 'generic/platform=iOS';
        $(xcrun --find docc) process-archive \
          transform-for-static-hosting /tmp/docbuild/Build/Products/Debug-iphoneos/swift-study.doccarchive \
          --hosting-base-path swift-study \
          --output-path docs;
        echo "<script>window.location.href += \"/documentation/swift-study\"</script>" > docs/index.html
    - name: artifact 업로드
      uses: actions/upload-pages-artifact@v1
      with:
        # docs 경로에 있는 것만 업로드
        path: 'docs'
    - name: GitHub Pages 에 배포
      id: deployment
      uses: actions/deploy-pages@v1

